flyinghead/flycast

core/rend/gles/CustomTexture.cpp

Since `reios_disk_id()` won't be called when platform is not dreamcast, so NAOMI games will have an empty `ip_meta`
Use the `reios_id` in config instead (value is `ip_meta.product_number` for DC, and `naomi_game_id` for NAOMI)

Custom Textures / Dump Textures supports NAOMI also

---

core/hw/sh4/modules/serial.cpp
core/rend/vulkan/vmallocator.cpp
core/rend/vulkan/vulkan_context.cpp

io.h is required by MSVC in order to use the `read`/`write` functions.
References:
- https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-read?view=vs-2019
- https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/read?view=vs-2019
Use platform-specific calling convention macros from https://github.com/flyinghead/flycast/blob/aac665e6177d91d4289b79e2f10a3b867daa46e6/core/khronos/vulkan/vk_platform.h#L49-L69
in `core/rend/vulkan/vmallocator.cpp` and `core/rend/vulkan/vulkan_context.cpp`. Fix build issues in MSVC.

msvc build fixes

---

core/oslib/audiobackend_libao.cpp

```
/home/runner/work/reicast-emulator/reicast-emulator/core/oslib/audiobackend_libao.cpp: In function ‘u32 libao_push(const void*, u32, bool)’:
/home/runner/work/reicast-emulator/reicast-emulator/core/oslib/audiobackend_libao.cpp:27:21: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
ao_play(aodevice, (const char*)frame, samples * 4);
^~~~~~~~~~~~~~~~~~
In file included from /home/runner/work/reicast-emulator/reicast-emulator/core/oslib/audiobackend_libao.cpp:4:0:
/usr/include/ao/ao.h:119:23: note:   initializing argument 2 of ‘int ao_play(ao_device*, char*, uint_32)’
int                   ao_play(ao_device *device,
^~~~~~~
```

Compilation fix for ao audio backend

---

core/log/ConsoleListenerDroid.cpp
core/log/ConsoleListenerNix.cpp
core/log/ConsoleListenerWin.cpp
core/windows/winmain.cpp
shell/linux/Makefile

Allow windows pty like terminals to use Nix ConsoleListener, e.g. mintty used by msys2 and cygwin.
Fix windows logging timestamps, so they start from 00:00:000 like the linux version.
If using Nix ConsoleListener on windows, turn off buffering of stderr.

let windows terminals use Nix ConsoleListener, fix windows timestamp

---

.travis.yml
shell/android-studio/build.gradle
shell/android-studio/gradle/wrapper/gradle-wrapper.properties
shell/android-studio/reicast/build.gradle
shell/android-studio/reicast/src/main/jni/Application.mk
shell/android-studio/travis-build.sh
shell/android-studio/travis-release.sh

- Set NDK version to 21.0.6113669 as it is currently the only one which supports the "-static-openmp" flag set in Android.mk
- Remove instructions related to Google Play since Flycast is not published there.
- Update Gradle and Android Grade plugin (better support for CMake)
- Update build tools and sdk to version 28. The lastest version (29) is not supported because the access to /dev/ashmem has been restricted (source: https://developer.android.com/about/versions/10/behavior-changes-10#shared-memory)
- Simplify .travis.yml to handle these changes (build example: https://travis-ci.org/github/scribam/reicast-emulator/builds/671048323)

Android build update

---

core/hw/modem/picoppp.cpp

If another process is using the UDP port, infinite WSAEINVAL error appears.

[MODEM] avoid WSAEINVAL error

---

core/hw/naomi/naomi_m3comm.cpp
core/network/naomi_network.cpp

- MSVC doesn't have `ssize_t`
- `u8 buf[packet_size];` generates https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2131?view=vs-2019

Compilation fixes for MSVC

---

core/archive/7zArchive.h
core/archive/archive.cpp

Compilation fix for MSVC + enable 7zArchive, this file was previously out of the scope of my CMake build.

Enable 7zArchive for MSVC

---

shell/apple/emulator-osx/emulator-osx/AppDelegate.swift
shell/apple/emulator-osx/emulator-osx/osx-main.mm

Adds the ability to launch multiple Flycast from menu or `Cmd+N`
New instances will show the running "instance number" on the dock icon's badge
Since Flycast on macOS uses the non configurable `~/.reicast`as config + data folder path, now it will create subfolder named with the instance number for additional instances.
Known issue: 
Instances must be created in sequential order. If user opens `Instance 2` and then quit `Instance 1`, the next created instance will also be `Instance 2`, resulting two `Instance 2` are running.
(The icon badge can reflect this clash)

[macOS] Enable "New Instance" in File and Dock menu

---

core/core.mk

These GNU extensions are not required currently and can lead to cross-platform issues

Use C++11 without GNU extensions

---

CMakeLists.txt

Disable `pkg-config` in macOS as suggested in https://github.com/flyinghead/flycast/issues/111
root cause: `macos-10.15/20200829.1` has `pkg-config` now, but `macos-10.15/20200825.1` doesn't, so even the exact same commit failed in my fork (Github built it with 20200829.1)

Fixes Github macOS build

---

core/rend/game_scanner.h
core/rend/gui.cpp
core/rend/gui_util.cpp

Since there are different players reported similar issue to me, I decided to improve it thru UI.
When the Content Location is set to root or any big folder, it will take forever to discover the games.
Currently Flycast will just show a blank static page, although it is actively recursively searching for games. 
I've added a counter to track and will show the below warning. After clicking "Reselect", user can select a new Content Location directly.
And for better folder navigation + discovery, relevant files will be shown in unselectable grey text inside the directory selector:

Display warning to user when it takes too long to find a game

---

.github/workflows/android.yml
.github/workflows/c-cpp.yml

- Bump actions/cache to v2
- Remove git fetch since it is not necessary anymore, see https://github.com/actions/checkout/pull/258 for details

GitHub Actions update

---

core/rend/gui.cpp
core/rend/gui.h
core/sdl/sdl.cpp
shell/apple/emulator-osx/emulator-osx/osx-main.mm

Windows:
Since SDL2 does not support `SDL_WINDOW_ALLOW_HIGHDPI` yet (https://github.com/libsdl-org/SDL/issues/2119), use `SetProcessDpiAwareness` to make Flycast "DPI aware" + use correct DPI Scaling for rendering now.
Mac:
Calculate the correct scaling factor by using the `scaled resolution / native resolution`.
p.s. `SDL_GetDisplayDPI()` is incorrect on macOS since it is relying on the `backingScaleFactor`
https://github.com/libsdl-org/SDL/issues/3446: [actual commit](https://hg.libsdl.org/SDL/rev/3b03741c0095)

HiDPI mode for Windows and proper scaling on macOS

---

core/deps/chdr/chd.c

I was getting "Bus Error" on my RK3328 32-bit build. And gdb points to some chd/lzma code.
I noticed that the same chd game does not have this issue using lr-flycast. After checking the lr-flycast libchdr code I see there's one additional commit e3b8bc9 by @rtissera that is not in the standalone flycast repo.
So this is to incorporate that commit. After this change my CHDv5 games no longer crash with Bus Error.
I made a patch for Batocera, @rtissera had a look at that and thought it was fine.

Incorporate lr-flycast@e3b8bc9: Fix CHD alignment issues

---

.github/workflows/c-cpp.yml

I guess it was disabled because of build issues with zlib

GitHub Actions: Enable i686-pc-windows-msvc build

---

core/rend/gles/glcache.h

Currently, the code below is never called (condition always false) because of `_texture_cache_size = 0;` few lines before
https://github.com/flyinghead/flycast/blob/2b41d9684f40052030b9af9d97710b2f34e352ff/core/rend/gles/glcache.h#L209-L213

glcache: call glDeleteTextures if texture cache size > 0 during reset

---

.gitmodules

See https://github.com/spurious/SDL-mirror/issues/15
After this update, run
```
git submodule sync
git submodule update --init --recursive
```
to use the new url.

deps: use official SDL url for submodule

---

CMakeLists.txt
core/deps/patches/SDL.patch

Also fix a minor warning during `git apply`
```
D:/a/flycast/flycast/core/deps/patches/SDL.patch:52: space before tab in indent.
SDL_MouseID mouseID;
warning: 1 line adds whitespace errors.
```
https://github.com/flyinghead/flycast/runs/2640224149#step:8:47

cmake: fix sdl compilation with Ninja + MSVC

---

CMakeLists.txt
core/rend/gui.cpp
shell/apple/emulator-osx/reicast-osx.xcodeproj/project.pbxproj

- [cmake] Use static library for SDL2
- [cmake] Use "Flycast" as app name
- [Xcode] Reimport zlib
- [Xcode] CoreHaptics.framework for SDL2
- Update platform string from `OSX` to `macOS` in About page

Fix macOS cmake & Xcode project

---

CMakeLists.txt

Swift 5 is introduced in macOS 10.14.4

Force cmake to add rpath to support macOS without Swift 5 Runtime

---

.cirrus.yml
.github/workflows/c-cpp.yml

With the libchdr's update (https://github.com/flyinghead/flycast/commit/54c492cac6e06ced7a27544ace86ea275c84010d) using dr_flac, this package is no longer required to build Flycast

ci: remove flac package

---

core/input/gamepad_device.cpp
core/input/gamepad_device.h
core/input/mapping.cpp
core/input/mapping.h
core/nullDC.cpp
core/rend/gui.cpp

Originally featured in Flycast Dojo so that players do not have to change controller mappings between game challenges on different systems. Should also be convenient outside the scope of netplay.
* Creates separate *Dreamcast* and *Arcade* profiles for each physical device upon assignment
* Falls back to default mapping if `.cfg` file if ending in `_arcade` is unavailable
* Adds *Unmap* button to  controller mapping menu

Controller Mapping: System Profiles & Unmap Button

---

core/hw/aica/aica_if.cpp

* Real Time Clock set to static value when GGPO is enabled. Useful for games when savestates are not loaded on boot.

ggpo: static rtc when ggpo is enabled

---

shell/apple/emulator-ios/plist.in

This value needs to exist in the plist file so AltServer can replace it with the device's UDID on install. 
Reference from DolphiniOS - https://github.com/OatmealDome/dolphin/commit/7f0e826558ad22009083ced6590d1e8a41d39d1b

[BUGFIX] Add ALTDeviceID to iOS Info.plist

---

CMakeLists.txt
core/cfg/option.cpp
core/cfg/option.h
core/hw/maple/maple_devs.cpp
core/hw/maple/maple_devs.h
core/input/gamepad_device.cpp
core/input/gamepad_device.h
core/rend/gui.cpp
shell/apple/emulator-ios/emulator/EmulatorView.mm
shell/apple/emulator-ios/emulator/FlycastViewController.mm
shell/apple/emulator-ios/emulator/ios_gamepad.h
shell/apple/emulator-ios/emulator/ios_keyboard.h
shell/apple/emulator-ios/emulator/ios_mouse.h

This PR adds in GCMouse support on iOS versions 14+
- Updated setRelPos/SetRelativeMousePosition to accept floats instead of ints
- Old IOSMouse is now IOSTouchMouse
- To differentiate better in settings I set the name to `Touchscreen (Mouse)`
- On iOS 14+ the app will now lock and hide the mouse cursor
- On pause/terminate this is set back to false so the user can navigate using mouse
- Added an option to invert external mice
- This is only available on iOS
- The trackpad on the iPad Smart Keyboard sends values inverted by default it seems. I didn't test with any other mice, but figured this option would be nice if the user feels like their mouse is wrong
https://user-images.githubusercontent.com/4458812/133198573-b939896f-ead3-46c7-89f8-2acf1e56659e.mp4

[iOS] GCMouse support

---

CMakeLists.txt
core/sdl/sdl.cpp

Hey,
For gamecontrollerdb.txt to be used searched correctly the file has to be loaded before the SDL init of input contollers.
Also,
Emuelec doesn't have the correct search path and the change enables Emuelec to retrieve the correct file.

Sdl controller fix

---

CMakeLists.txt
shell/apple/emulator-ios/AltKit/CMakeLists.txt

- `IOS` is not defined before `project(flycast)` so `CMAKE_SYSTEM_NAME` must be used
- Setting `CMAKE_SYSTEM_PROCESSOR` for iOS  is no longer required since `libchdr` has this change : https://github.com/rtissera/libchdr/pull/57/files
- Reset AltKit's CMakeLists.txt with upstream
- iOS builds now target `arm64-apple-ios12.0` everywhere

cmake: iOS minor fixes

---

.github/workflows/c-cpp.yml

ci: use msys2 only for mingw builds

---

.gitlab-ci.yml
core/windows/unwind_info.cpp

This fixes a compilation issue when cross-compiling the Windows core on a Linux environment. Header include for dbghelp is corrected so that it works in a case-sensitive environment.
It also adds a .gitlab-ci.yml file which we need so the Gitlab CI can build the cores.

(Libretro) CI integration - and necessary fix for compiling Windows

---

core/cfg/option.cpp
core/cfg/option.h
core/lua/lua.cpp
core/rend/gui.cpp

Allows users to select a lua file by name. 
I think that the override option is not necessary / tedious UX but 
a) did not want to let users hang themselves by accident 
b) did not want to step on toes if you intended flycast.lua to work in some particular way I had not anticipated.
Let me know if I should:
1) Remove override
2) Just set the config variables default to "flycast.lua"
3) change lua.cpp to just look for the config option instead.

Allows override of flycast.lua file

---

core/deps/breakpad/src/client/linux/handler/exception_handler.cc

As outlined by Samuli Piippo in the qtwebengine chromium patch (https://codereview.qt-project.org/c/yocto/meta-qt6/+/378728/2/recipes-qt/qt6/qtwebengine/chromium/0004-breakpad-fix-build-with-glibc-2.34.patch), SIGSTCKZ is no longer being compile time constant in glibc-2.34. The proposed fix compiles on my end and I have not tested on a linux distro with an earlier version of glibc.

Fix linux breakpad issues when glibc-2.34 is installed

---

CMakeLists.txt
core/linux-dist/main.cpp

This PR has two commits.
1. Added `EXCLUDE_FROM_ALL` for glslang and xbyak so that they aren't installed.
2. Added an install target for flycast, I used the AUR pkgbuild and the flathub build as reference for what files should be installed.
Note:
* Should any files in the `shell/linux/mappings/` directory be installed and if so where?
* I hooked up `${CMAKE_INSTALL_SYSCONFDIR}` and `${CMAKE_INSTALL_DATADIR}`, but I am unsure what files should be installed there if any?

 cmake: Add an install target

---

shell/apple/emulator-ios/LLDBInitFile
shell/apple/emulator-ios/emulator/ios_main.mm
shell/apple/emulator-osx/LLDBInitFile
shell/apple/emulator-osx/emulator-osx/SDLMain.mm
shell/apple/generate_xcode_project.command

add `task_set_exception_ports()` to ignore `EXC_BAD_ACCESS`
add `process handle -s false SIGBUS` into lldbinit to ignore `SIGBUS`
add `generate_xcode_project.command` to create debug friendly macOS/iOS xcodeproj with the new lldbinit file
Tested on Intel macOS 10.15, Apple Silicon macOS 11, iOS 14.2

Make Flycast debug friendly with Xcode

---

shell/libretro/libretro_core_options.h

- Changes the main category sublabels to match RetroArch's style.
- Adds a missing period, as reported in Crowdin.
- Adds an extra minor description to the Language setting.

[Core options text] Typo fixes and minor style changes

---

shell/libretro/audiostream.cpp
shell/libretro/libretro.cpp

At present, the libretro core has two issues related to the usage of the audio batch callback:
- When threaded rendering is enabled, the audio batch callback is used on a background thread. The libretro API does not guarantee the safety of this callback unless it is used on the main thread
- Audio samples are sent in batches of 256 frames, whereas the frontend expects exactly `(sample_rate/fps)` sample frames per call of `retro_run()`. This means that in each `retro_run()` interval, a smaller or greater number of samples are sent than are expected. The way that RetroArch syncs on audio means that uneven audio sample pacing affects video frame pacing - and in general, irregular audio pacing 'stresses' the frontend audio buffer
This PR moves the audio batch callback onto the main thread via …

(libretro) Move audio batch callback onto main thread + improve audio sample pacing

---

.github/workflows/c-cpp.yml

Each ci build will now have its own cache. Should fix the following issue when two jobs share the same cache key

ci: fix ccache cache key

---

.github/workflows/c-cpp.yml

Junk folders "artifact/bin/Flycast.app" appear since #450

Remove junk folder when packaging macOS app

---

CMakeLists.txt

Change introduced in https://github.com/flyinghead/flycast/commit/73fa0e3efcb27220db976f4becf1679ec8639352
This makes [recent Flatpak builds to fail](https://github.com/flathub/org.flycast.Flycast/commits/master):
`ninja: error: '/usr/lib/x86_64-linux-gnu/libSDL2.a', needed by 'build/flycast', missing and no known rule to make it`
This change won't impact macOS nor Win32.
---
I have tested locally to build the Flatpak, it works. However, I don't know the state of static Flycast binaries for Linux, and this recent commits were not about that anyway.

Fix missing `libSDL2.a` static library on Linux

---

core/rend/gles/postprocess.cpp

Added a missing `ifndef` guard for `glBindVertexArray`, useful for GLES2-only builds.
Similar guards exists in the same source file (`postprocess.cpp`), this one probably slipped.

postprocess: fix GLES2-only build

---

core/deps/libretro-common/include/libretro.h
shell/libretro/libretro_core_options.h

Also, fixes a _tiny_ mistake I made, resulting in Swedish being used instead of Slovak. Whoopsie.

Enable Indonesian, Swedish and Ukrainian localisations

---

README.md

Add installation instructions for flycast via Homebrew on MacOS.

Add installation on MacOS via Homebrew

---

core/deps/picotcp/stack/pico_socket.c

Backport https://github.com/virtualsquare/picotcp/commit/529074aab4f53a87426673548d6793ced666b6ed
Fix the following MSVC debug build issue:
```
pico_socket.c.obj : error LNK2019: unresolved external symbol pico_ipv6_source_dev_find referenced in function pico_socket_xmit_one
```

deps/picotcp: pico_ipv6_source_dev_find requires PICO_SUPPORT_IPV6

---

.github/workflows/c-cpp.yml
.github/workflows/uwp.yml

windows-latest workflows now use Windows Server 2022, migration is done according to https://github.com/actions/virtual-environments/issues/4856

ci: use windows-latest

---

core/rend/gui.cpp

This can be used to get a smoother image (supersampling) on 1440p and 4K displays. The 9× setting is also suited for native resolution rendering on 8K displays, or 4× supersampling on 4K.
The setting description was also made more extensive:
*Supersampling above 4× is not effective because the viewport does not have mipmaps to work with. Generating mipmaps for high-quality real-time downsampling is too slow to be worth considering, since 4× supersampling is very expensive already. If further antialiasing is desired, MSAA or FXAA could be implemented and could be used on top of supersampling.*
I tested this change locally and it works as expected on a 2560×1440 monitor:
*Click to view at full size (and click again to show at pixel-perfect scale in the browser). Look at the controller …

Add 6×, 7×, 8× and 9× options for internal resolution

---

core/cfg/option.cpp
core/cfg/option.h
core/lua/lua.cpp
core/rend/gl4/gldraw.cpp
core/rend/gles/gldraw.cpp
core/rend/gui.cpp
core/rend/vulkan/texture.h
shell/libretro/libretro_core_options.h
shell/libretro/option.cpp

The new texture filter option can be set to:
- Default (keeps the game's intended filter mode).
- Force Nearest-Neighbor (crisper appearance).
- Force Linear (smoother appearance).
Additionally, mipmapping can now be enabled on nearest neighbor-filtered textures (which is used if nearest-neighbor filtering is enabled, including with anisotropic filtering).
Anisotropic filtering was already implemented in both OpenGL and Vulkan, but it was not exposed in the GUI.
I've only tested this on one game so far. Also, apologies for the relatively large change, but it was easier for me to consolidate both the texture filtering setting and anisotropic filtering changes. I can make two separate PRs if desired.
This closes https://github.com/flyinghead/flycast/issues/563.
- Implement on Direct3D. I …

Add texture filter override setting, expose anisotropic filtering

---

core/hw/aica/aica.cpp
core/hw/aica/aica_mem.cpp

```
aica_if.cpp.obj : error LNK2019: unresolved external symbol "unsigned int __cdecl aicaReadReg<unsigned int>(unsigned int)" (??$aicaReadReg@I@@YAII@Z) referenced in function "unsigned int __cdecl ReadMem_aica_reg<unsigned int>(unsigned int)" (??$ReadMem_aica_reg@I@@YAII@Z)
arm_mem.cpp.obj : error LNK2001: unresolved external symbol "unsigned int __cdecl aicaReadReg<unsigned int>(unsigned int)" (??$aicaReadReg@I@@YAII@Z)
aica_if.cpp.obj : error LNK2019: unresolved external symbol "void __cdecl aicaWriteReg<unsigned int>(unsigned int,unsigned int)" (??$aicaWriteReg@I@@YAXII@Z) referenced in function "void __cdecl WriteMem_aica_reg<unsigned int>(unsigned int,unsigned int)" (??$WriteMem_aica_reg@I@@YAXII@Z)
arm_mem.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl …
```

msvc: fix linking issues in debug build

---

CMakeLists.txt

This library has been added in commit 043175ae with multitouch support in osx_keyboard.h. Then, this file has been removed in commit da3ed74c so the multitouch library is no longer required.

cmake/macos: remove multitouch library

---

shell/libretro/audiostream.cpp

At present, the libretro core gathers all audio samples that are generated by `emu.render()` during a call of `retro_run()` and uploads them to the frontend at the end of the frame. The problem here is that one call of `retro_run()` does not necessarily correspond to one "frame's worth" of emulation (i.e. `1 / frame_rate` virtual seconds of runtime). Flycast can stop rendering frames for arbitrary lengths of time, which means `retro_run()` can spin for many  "frame's worth" of emulation - which in turn means that the gathered audio sample buffer can grow arbitrarily large. This can be observed (for example) in the games `Tony Hawk's Pro Skater 2` (at the loading screen) and `House of the Dead 2` (when pausing cinematics), where a single call of `retro_run()` can produce hundreds of …

(libretro) Limit maximum number of audio samples that can be uploaded per call of retro_run()

---

shell/libretro/audiostream.cpp
shell/libretro/libretro.cpp
shell/libretro/libretro_core_options.h

This PR adds a new `Detect Frame Rate Changes` option to the libretro core. When enabled, the core will detect frame rate changes that are a factor of the nominal display refresh rate (e.g. 60 <-> 30 <-> 20 fps, etc. for NTSC content) and notify the frontend, such that the frontend can call `retro_run()` with proper timing instead of relying on over-saturation of the audio buffer to control game speed.
When used in conjunction with RetroArch's new automatic `VSync Swap Interval` feature (https://github.com/libretro/RetroArch/pull/13927), this enables **perfect** frame pacing for 30 fps and 20 fps games on a 60 Hz display (and for 30 fps content on a 120 Hz display).
Caveats:
- The `Detect Frame Rate Changes` option is only available when `Auto Skip Frame` is disabled
- Frame rate …

(libretro) Add option to detect and notifiy frontend of internal frame rate changes (60 <-> 30 <-> 20 fps, etc.)

---

core/cfg/option.cpp
core/cfg/option.h
core/rend/gui.cpp
core/rend/gui_chat.h

Adds auto chat window timeout option. For players using arcade cabinets who are unable to reach keyboard to exit chat window.

GGPO Chat Window Timeout

---

.github/workflows/c-cpp.yml
CMakeLists.txt
shell/apple/libomp.rb

- Bumping cmake to 3.16 (I'm not sure why the current cmake version has problem with OpenMP)
- Providing a universal build of OpenMP for Flycast to link

Enable Texture Upscaling on macOS

---

core/rend/gui_chat.h

* DIsables chat window timeout after you respond to chat message. Prevents it from disappearing during actual conversation.

chat: disable window timeout after you respond to message

---

CMakeLists.txt
core/rend/dx11/dx11context_lr.cpp
core/wsi/libretro.cpp
core/wsi/libretro.h
shell/libretro/libretro.cpp

Since it's possible to build a Vulkan only core, I figured why not offer the option for a DX11 only core?
This is mainly intended to be used with Xbox systems since DX11 is the only usable API for those systems.
As this is my first pull request, any reviews or comments are welcomed.

(Libretro) Allow a DX11 only core to be built.

---

README.md

- The original reicast link is down, so I think it's better to link the archived GitHub repo for those interested in checking the emulator for historical purposes.
- We can now emulate Naomi 2! So why not have the Readme reflect that?
- Small formatting touches.

Readme Updates.

---

shell/apple/emulator-osx/emulator-osx/SDLMain.h
shell/apple/emulator-osx/emulator-osx/SDLMain.mm

Category method won't be called when the parent class (`NSApplication`) has the same method

[macOS] Handle Quit menu item properly

---

core/emulator.cpp

* Prevents extra maple devices from being loaded when switching between systems between games (i.e., Arcade -> DC)

load game: destroy old maple devices before create call

---

.github/workflows/c-cpp.yml
core/hw/maple/maple_cfg.cpp

- Add MacPorts as alternative link for Vulkan SDK
- `mcfg_DestroyDevices()` is no longer needed in `mcfg_CreateDevices()`

Add Vulkan download mirror and DRY

---

core/log/ConsoleListenerNix.cpp
core/log/LogManager.cpp
shell/apple/emulator-osx/emulator-osx/osx-main.mm

- Prints UTF-8 string properly
- Supports color (by emoji) in Console.app and Xcode console
- Fixes empty `flycast.log`

macOS logging

---

shell/uwp/package.appxManifest

This adds three UWP app capability declarations to Flycast, these being `runFullTrust`, `broadFileSystemAccess`, and `expandedResources`.
`runFullTrust` gives Flycast full trust permission rights to the device it's installed, while `broadFileSystemAccess` allows Flycast's built-in file explorer to take advantage of the full trust permissions it has. This fixes Flycast's built-in File Explorer, allowing the user to choose more than two directories to store their games in.
`expandedResources` gives Flycast access to more of the system's CPU capabilities, which can result in performance boosts since we can now use more of the CPU's power than before.

(UWP) Add Additional Rescap Capabilities

---

core/emulator.cpp

Game boots to BIOS if the incorrect "Broadcast" region is selected.

Switch broadcast region for San Francisco Rush 2049 and Sega Smash Pack - Volume 1

---

.github/workflows/uwp.yml
CMakeLists.txt

This disables the Vulkan renderer for UWP builds directly on the CMakeLists.txt file rather than disabling it during build time. 
Since this is how it's handled for the Switch workflow, I figured UWP could be handled like this as well. Not to mention that having to input one less build flag is certainly a nice thing to have. :)
Since Vulkan was always disabled for UWP anyway, there shouldn't be any differences in the final builds.

(UWP) Build Tweaks

---

shell/uwp/package.appxManifest

Seems this flag is only relevant when using an Xbox App, it does next to nothing for apps set as Games.
Plus it causes a very strange buggy behavior with any app that uses it, input isn't suspended when using the Xbox guide. So you can accidentally open a game in Flycast while checking your friends list and yeah, that's bad.

(UWP) Remove expandedResources

---

CMakeLists.txt

Found this while wondering why "About" screen shows a commit hash that doesn't seem to exist - turns out if you run CMake with the -S option to point at a directory with the source, then the git commands execute in the directory you ran the cmake command in, instead of in the repository directory.
This can fail or even succeed with a hash from an unrelated repository (in my case this is what happened, it fetched the [hash of the AUR package](https://aur.archlinux.org/cgit/aur.git/commit/?h=flycast-git&id=69ab6976b143f05249ffeaaa03bdefd1715e30d4) instead, and funnily enough I'm not the only person this happened to, see [last video on this list](https://www.restartsyndrome.com/replays.php?id=68&mode=Hard%20Mode) ).

cmake: execute git commands in the source directory

---

shell/libretro/libretro.cpp
shell/libretro/libretro_core_options.h
shell/libretro/libretro_core_options_intl.h

Although DX11 only builds are now possible, the way the libretro port handles when to show Per-Pixel settings still needed some tweaks as a result. Currently, this option is only enabled if the build is made with either the `HAVE_OIT` flag, or with the Vulkan Renderer enabled. Although DX11 is perfectly capable of Per-Pixel Rendering, the options were simply not available due to this oversight. 
This PR fixes that, allowing Per-Pixel to be used with DX11-only builds. This was tested on an Xbox Series X, in which results were comprable to the standalone UWP port. But Windows testing is certainly welcomed!

(Libretro) Enable Per-Pixel Options on DX11 builds

---

shell/apple/libomp.rb

Fix the following warnings:
- https://github.com/flyinghead/flycast/actions/runs/3188477252/jobs/5201189329#step:8:11
```
Warning: libomp 14.0.6 is available and more recent than version 14.0.0.
```
- https://github.com/flyinghead/flycast/actions/runs/3188477252/jobs/5201189329#step:10:15422
```
ld: warning: object file (/usr/local/lib/libomp.a(kmp_csupport.cpp.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (/usr/local/lib/libomp.a(kmp_ftn_cdecl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (/usr/local/lib/libomp.a(ompt-general.cpp.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (/usr/local/lib/libomp.a(kmp_alloc.cpp.o)) was built for newer …
```

libomp.rb: update and set min macosx version to 10.9

---

CMakeLists.txt

Fix warning "clang: warning: argument unused during compilation: '-static-openmp' [-Wunused-command-line-argument]"
https://github.com/flyinghead/flycast/actions/runs/3188477252/jobs/5201189329#step:10:15421

cmake: remove "-static-openmp" for apple

---

core/emulator.cpp
core/hw/mem/mem_watch.h

When GGPO is active, `elanWatcher.protect()` -> `ElanRamWatcher::protectMem()` is called
Peer disconnecting will call `dc_reset(true)`, elan ram will be reinitialized to 0, and would crash since it is still protected.
elan.cpp:
```cpp
void reset(bool hard)
{
if (hard)
{
memset(RAM, 0, ELAN_RAM_SIZE);
state.reset();
}
}
```
This is an attempt to fix this issue without a deep understanding, please close the PR and consider this as an issue if appropriate.

Fix crash on GGPO disconnecting, when resetting elan memory

---

core/rend/gui.cpp

Make it easier for user to discover how to remove black bars, related: #768

Add Aspect Fit & Aspect Fill description for Widescreen and Super Widescreen

---

CMakeLists.txt

- Copy-paste the post build commands without `$<CONFIG>` which does not work with Ninja
- `dsymutil` command added to generate the dSYM file. Ninja does not generated this file automatically like Xcode

macos: fix cmake post build command with ninja

---

core/rend/vulkan/vulkan_context.cpp
core/wsi/sdl.cpp

Dirty fix for #769, verified by a gundam tester
Since patching the EDID by every user is a bit tedious...
Before the patch:
After the patch:

Fixing Steam Deck's wrong dpi caused by incorrect 60mm * 60mm EDID

---

core/rend/vulkan/vulkan_context.cpp
core/wsi/sdl.cpp

For unknown reason, EDID is hidden in Game Mode, so xrandr cannot fetch the 60mm * 60mm dimension in `Detailed Timing Block`, and `Display Product Name`
As a fallback, Game Mode would use the `Screen Size` info instead, and the emulated name `XWAYLAND0`
Unlike the incorrect 60mm * 60mm dimension inside the Timing Block, only some Steam Deck's `Screen Size` has the incorrect 6cm * 5cm dimension (usually it would report as 10cm * 15cm, depends on manufacturing batch)
This is an update of https://github.com/flyinghead/flycast/pull/796, fixes https://github.com/flyinghead/flycast/issues/769 again

Fixing Steam Deck's wrong dpi caused by incorrect 6cm * 5cm EDID (Game Mode)

---

core/rend/dx11/dx11context.cpp

Currently the ui switches between 2 different ui scales depending on if the display is 4k or something else.
This leads to the UI being too big at 720p and too small at 1440p.
This pr fixes that by taking the display width, dividing it by 1920p and then using that as a multiplier for the display scale.
4k without the pr:
1440p without the pr:
1080p without the pr:
720p without the pr:
720p with the pr:
1080p with the pr:
1440p with the pr:
4k with the pr:

make Xbox display scale scale with res instead of just switching between 2 presets for 1080p and 4k

---

CMakeLists.txt
core/build.h
core/cfg/option.h
core/hw/pvr/Renderer_if.cpp
core/rend/dx11/dx11context_lr.cpp
core/rend/gui.cpp
core/wsi/switcher.cpp

Adds D3D9 as a configurable option so we don't need to install the DirectX 9.0c SDK if we don't want it for development. Also added D3D11 for completion's sake only.

Added USE_DX9 and USE_DX11 as configurable options in CMake

---

core/hw/sh4/modules/serial.cpp

Opens up an external console for serial output on Windows, since the project isn't configured with /SUBSYSTEM:CONSOLE so stdout/stderr isn't attached to the launching terminal.

External windows serial console

---

core/debug/debug_agent.h
core/debug/gdb_server.cpp
core/emulator.cpp
core/emulator.h

Implements ranged stepping using vCont packets, which is a much faster way to step over multiple instructions to get to the next source line (otherwise it's a flurry of step/stop/get pc/step/stop/get pc over the network, with all the thread stop/resume overhead that comes with it).
Fixed up the thread futures not being tested for validity - these get into a bad state with a combination of GDB start/stops.
I've also added an enum for breakpoint type, with a view to add support for the rest at a later date.

Support for GDB vCont and ranged stepping

---

shell/linux/org.flycast.Flycast.metainfo.xml

```
$ appstreamcli validate org.flycast.Flycast.metainfo.xml
W: org.flycast.Flycast:~: category-invalid Games
✘ Validation failed: warnings: 1, pedantic: 5
```

metainfo: fix wrong category name

---

.gitlab-ci.yml
core/emulator.cpp
shell/libretro/libretro.cpp

Static variables can get left around and reused following dlclose/dlopen (the manpage for dlclose is deliberately unclear about whether that will happen). RetroArch on OSX crashes when trying to load flycast a second time because the core fails to reinitialize, because it thinks it is terminated.

Fixes for libretro on Mac

---

CMakeLists.txt
core/windows/winmain.cpp

And `nowide::args` to convert arguments to UTF-8

sdl: use target SDL2main

---

core/rend/vulkan/utils.h

Verified with `glslangValidator`, `#version 430` can be used instead of `#version 450`

vulkan: lower shader version requirement

---

core/sdl/sdl.cpp

_WIN32 is one of the predefined macros https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170
See also https://stackoverflow.com/a/74084728

sdl: use _WIN32

---

.github/workflows/android.yml
.github/workflows/c-cpp.yml

Fix warnings from https://github.com/flyinghead/flycast/actions/runs/4192576505 and https://github.com/flyinghead/flycast/actions/runs/4192576503
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: mathieu-bour/setup-sentry-cli@1.2.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

ci: update mathieu-bour/setup-sentry-cli

---

core/hw/aica/dsp_x64.cpp
core/hw/arm7/arm7_rec.cpp
core/hw/naomi/naomi_m3comm.cpp
core/hw/sh4/dyna/driver.cpp
core/khronos/GL4/gl3w.c
core/linux/context.cpp
core/sdl/sdl.cpp

Before I submit a port for OpenBSD for flycast, I would like to submit some patches. On OpenBSD 7.2 -current, BSS is now immutable and mprotect can't work. Mark it as mutable to allow mprotect to work. This is the main change for OpenBSD as of 7.2 -current (I had it working in 7.1.)
I applied a similar fix for the desmume port:
https://marc.info/?l=openbsd-ports&m=167055339501257&w=2
More information on mimmutable:
https://marc.info/?l=openbsd-tech&m=166874067828564&w=2
Moreover, I've included other fixes.  I'm able to run flycast on OpenBSD with this and some other cmakelists changes, which I have omitted for ease of review.
Original issue where you helped me: https://github.com/libretro/flycast/issues/624

openbsd patches

---

.gitlab-ci.yml

When setting up the libretro steam pipeline, because some cores have different build settings across x86_64/arm64, it's easier to build them individually.

Only compile x86_64 for osx-x86_64, rather than universal

---

shell/uwp/package.appxManifest

- Fixes some indentation in the file.
- Adds back `expandedResources` which was originally removed in PR #753 since it seemed to cause a bug in the Xbox UI. Turns out the issue was not caused by this capability, but by an OS Update that caused this issue in Retail Mode only. This issue is not present in Dev Mode, so I might as well add it back.

(UWP) AppxManifest Tweaks

---

.github/workflows/android.yml
.github/workflows/c-cpp.yml
.github/workflows/switch.yml
.github/workflows/uwp.yml

https://github.com/aws-actions/configure-aws-credentials/blob/main/CHANGELOG.md
> Version bump to use Node 16 by default.
Should fix the following warnings in Actions:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: aws-actions/configure-aws-credentials@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

ci: bump aws-actions/configure-aws-credentials

---

core/hw/naomi/multiboard.h

These systems do not have pthread_condattr_setpshared/pthread_mutexattr_setpshared

naomi: netbsd/openbsd pthread fixes

---

core/log/StringUtil.h

Simplify building for OpenBSD otherwise:
> -I/usr/local/include is needed for the compiler to find iconv.h, as the base compiler does not look under /usr/local/include by default.
Source: https://citra-emu.org/wiki/building-for-openbsd/

remove unused iconv.h include

---

shell/apple/emulator-osx/emulator-osx/osx-main.mm

Original from https://github.com/flyinghead/flycast/pull/81, updated to be compatible with Multiboard implementation
p.s. All GUI app in macOS has `ppid = 1`, while forked process has `ppid = parent's pid`

[macOS] Update "New Instance" feature to be compatible with Multiboard

---

core/rend/gui.cpp
core/rend/gui_util.cpp

So it doesn't look like disabled

Set `header()` and `OptionArrowButtons()` alpha to 1.0f

---

core/rend/gui.cpp

"Covert art" → "cover art".
Despite how intriguing the concept of covert art may sound.

Typo in GUI.

---

shell/libretro/libretro.cpp

Added support for new controllers in the Libretro interface: 
- Maracas (RETRO_DEVICE_MARACAS)
- Fishing Controller (RETRO_DEVICE_FISHING)
- Pop'n Music (RETRO_DEVICE_POPNMUSIC)
- Race Controller (RETRO_DEVICE_RACING)
- Densha de Go! (RETRO_DEVICE_DENSHA)
Also did a bit of refactoring, mostly for readability, but also moving repeated code into functions.
Tested with RetroArch and another Libretro implementation.

Libretro: support for more controllers, code cleanup

---

.github/workflows/c-cpp.yml
.gitmodules

Fix libzip error `rend/gui.cpp:2941 E[BOOT]: Cannot open xxxxx.zip`, caused by Spout2 MinGW build linking MSVC Universal C Runtime.
Updated Spout2 to use remove the UCRT dependency
p.s. Ignore `brew update` error also

Fix Spout2 MinGW libzip error

---

core/rend/gui.cpp
shell/apple/emulator-osx/emulator-osx/SDLMain.mm
shell/apple/emulator-osx/emulator-osx/osx-main.mm

Menu search:
When using hotkey:
- Is the implementation of `NSMenu`'s action necessary?
- Yes, it is required for accessibility / automation / menu searching
- Is disabling the Edit menu when "text input is not in focus" necessary?
- No, but it is just a simple toggle. The proper way of implementing it would be detecting if text is actually highlighted before enabling the Copy menu. (like TextEdit)

macOS: Enable clipboard functions and corresponding menu items

---

CMakeLists.txt

https://github.com/flyinghead/flycast/actions/runs/5477993379/jobs/9977856592#step:12:209

cmake: exclude nowide tests from unit tests

---

core/rend/vulkan/vulkan_context.cpp
core/rend/vulkan/vulkan_context.h

- Using Vulkan-Hpp, we can simplify some calls to retrieve device properties
- `vkGetPhysicalDeviceProperties2` (used by `physicalDevice.getProperties2<vk::PhysicalDeviceProperties2, vk::PhysicalDeviceMaintenance3Properties>();`) requires to check if the device api version is >= 1.1.
> Physical-device-level functionality or behavior added by a [new core version](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#versions) of the API must not be used unless it is supported by the physical device as determined by [VkPhysicalDeviceProperties](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkPhysicalDeviceProperties)::apiVersion and the specified version of [VkApplicationInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec …

vk: modernize device properties retrieval

---

core/sdl/sdl.cpp

Clicks were swapped in GUI as SDL uses 2 for middle and 3 for right, and the GUI expects the opposite (minus 1).

Fix GUI SDL mouse buttons

---

.github/workflows/android.yml
.github/workflows/c-cpp.yml

The old command `upload-dif`/`upload-dsym` are [aliases](https://github.com/getsentry/sentry-cli/blob/da6b26a4769035059aae7d3ffa1710c883f8a2c6/src/commands/upload_dif.rs#L1) to the `debug-files upload` in `v2` of `sentry-cli`.

sentry: use new syntax for uploading files

---

core/input/mapping.cpp

`btn_trigger_left2` and `btn_trigger_right2` were mapped to port2.
So rename them to `btn_trigger2_left`, `btn_trigger2_right`.

[input] fix LT2/RT2 mapping save

---

CMakeLists.txt
core/rend/dx11/dx11context.cpp

I found that some players are using the integrated GPU:
This can be fixed by manually selecting the appropriate preference. 
But I guess we should use the high performance GPU by default.
Things to verify:

DX11: Use high performance GPU on Windows 10 (1803 or later)

---

core/input/gamepad_device.cpp
core/input/gamepad_device.h
core/sdl/sdl_gamepad.h
shell/android-studio/flycast/src/main/jni/src/android_gamepad.h

Only reduce the threshold for Dreamcast digital buttons, when the target axis is L2 (leftTrigger) or R2 (rightTrigger).
Fixes #1188.

Increase L2+ / R2+ trigger sensitivity for digital buttons

---

core/cfg/option.cpp
core/cfg/option.h
core/emulator.cpp
core/rend/gui.cpp
core/serialize.h
shell/libretro/libretro_core_options.h
shell/libretro/option.cpp
tests/src/serialize_test.cpp

This change adds support for the Dreamcast 32MB Mod as detailed here: [tsowell's original blog post](https://blog.ldtlb.com/2020/06/21/dreamcast-32mb-ram-upgrade.html) and 
[32MB Mod Wiki Page](https://dreamcast.wiki/32MB_RAM_expansion)
Image showing new setting:
[Support was added to KallistiOS](https://github.com/KallistiOS/KallistiOS/pull/82) (Open Source SDK for Dreamcast/NAOMI) for detection and usage of the 32MB modification in Janurary. 
Tested using the [KOS memtest32](https://github.com/KallistiOS/KallistiOS/blob/master/examples/dreamcast/basic/memtest32/main.c) example program.
32MB Mod Disabled:
```
This console has 16777216 bytes of system memory,
with top of memory located at 0x8d000000.
Beginning memtest routine...
Base address: 0x8c100000
Number of bytes to test: 15663104 …
```

Add Dreamcast 32MB RAM Mod

---

core/sdl/sdl.cpp

Quick fix for #1202 without introducing new GUI Option, should be ok if game which requires mouse capture won't map Left Ctrl / Left ALT as input?

Ignore Mouse Capture when Left Ctrl or Left ALT is mapped to a Dreamcast Key

---

CMakeLists.txt

https://github.com/flyinghead/flycast/blob/cb91ad3ae0c1291485892bf3a9663a2fd303ce83/core/lua/lua.cpp#L22
lua.hpp was added in lua 5.2
Fix Nintendo Switch compilation with latest devkitpro docker image (which includes lua 5.1)

lua: set minimum version required to 5.2

---

core/cfg/option.h
shell/libretro/option.cpp

Suppresses the following errors when the core is checking the core options:
> [ERROR] [Environ]: GET_VARIABLE: pvr.rend - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: rend.PerStripSorting - Invalid value.

[Libretro] Remove some "Invalid value" errors

---

core/hw/maple/maple_cfg.cpp

Currently when using "Racing Controller" you can select an expansion device from the GUI but it's not being created, this small PR fixes this.

Create expansion device for "Racing Controller"

---

CMakeLists.txt

Set minimum version required to 2.0.9 because of SDL_JoystickRumble
https://github.com/libsdl-org/SDL/releases/tag/release-2.28.5

deps: update sdl to version 2.28.5

---

CMakeLists.txt
core/sdl/sdl.cpp
shell/apple/emulator-osx/MacOSXBundleInfo.plist.in
shell/apple/emulator-osx/emulator-osx/SDLApplicationDelegate.h
shell/apple/emulator-osx/emulator-osx/SDLApplicationDelegate.mm

- Register file extensions for `openFile`, and supports the following actions
- Drag ROM to Application icon to launch the app
- Drag ROM to the running app's dock icon
- Drag ROM to the running app's window (applicable to all SDL platform by `SDL_DROPFILE`)
- Update `setupWorkingDirectory`
- macOS default cwd is a nonsense "/" for non-terminal application 
- Rename `SDLMain` to `SDLApplicationDelegate` to avoid confusion with the function `SDL_main()`
- some code cleanup

macOS Optimization

---

CMakeLists.txt

- Minor improvement to remove the  `_DEFAULT_SOURCE` defines
- Remove project related `CXX_EXTENSIONS ` to rely on the global `CMAKE_CXX_EXTENSIONS`

cmake: use CMAKE_CXX_EXTENSIONS for Nintendo Switch

---

shell/libretro/libretro.cpp

Input descriptors were not showing before, expect for the default controller, here's an example with "Arcade Stick":
Now it shows properly:
Plus some cleanups and added some missing `break;`.

[Libretro] Input descriptors fixes

---

core/emulator.cpp

South Park Rally US doesn't boot with PAL broadcast and vice-versa.

Broadcast override for South Park Rally

---

.gitmodules
core/rend/dx11/dx11_renderer.cpp
core/rend/dx11/dx11context.cpp
core/rend/dx11/dx11context.h
core/rend/gles/gles.cpp
core/rend/gui.cpp
core/rend/vulkan/vulkan_context.cpp
core/rend/vulkan/vulkan_context.h
core/windows/winmain.cpp
core/wsi/context.h
core/wsi/sdl.cpp
core/wsi/sdl.h
shell/apple/emulator-osx/emulator-osx/osx-main.mm

- Update Spout2 dep
- fixes [MINIDUMP-20Y](https://flycast.sentry.io/issues/4603889822/) / [MINIDUMP-21B](https://flycast.sentry.io/issues/4610185662/) / [MINIDUMP-21E](https://flycast.sentry.io/issues/4611071861/)
- No more `initVideoRouting()` calls in `GraphicContext` and gui, Spout/Syphon will be initiated on demand in render
- Dedup gui
- Windows:
- macOS:
- Both platforms:

Video Routing Revamp

---

core/rend/dx11/dx11_overlay.cpp
core/rend/gles/gldraw.cpp
core/rend/vulkan/overlay.cpp

Noticed while testing #1339, the on-screen VMU can get squished if the game decides to change its resolution.
Before:
After:

[Libretro] Fix VMU scaling for dynamic res games

---

.github/workflows/switch.yml
.github/workflows/uwp.yml
shell/android-studio/build.gradle
vcpkg.json

There is an issue with the latest devkitpro docker image that's why I locked the version.
- https://devkitpro.org/viewtopic.php?f=42&t=9532&sid=edf39fafcceeba2fa54876ae27f4b6af
- Logs: https://github.com/scribam/flycast/actions/runs/7766044323/job/21181417489

Android gradle plugin, SDL 2.30.0, devkitpro build image

---

core/cheats.cpp

using strtol here instead of strtoul when cheat code values are expected to be unsigned and are above 7fffffff breaks on platforms like Windows where long is 32-bit even on 64-bit platforms, capping out at 2147483647 and causing some (possibly quite a lot) of cheat codes to break.

cheats: fix parsing cheat codes on some platforms (like Windows)

---

.gitmodules
CMakeLists.txt

Use upstream repository
Changelog:
- Add support for zstd codec
- Fix a memory leak with the huffman decoder 
- Update dr_flac to version 0.12.42
- Update zlib to version 1.3.1

deps: update libchdr

---

core/cfg/option.cpp
core/cfg/option.h
core/hw/pvr/ta_vtx.cpp
core/rend/gui.cpp
shell/libretro/libretro_core_options.h
shell/libretro/option.cpp

Helps with texture bleeding case when upscaling. Disabling it can help if pixels are warping when upscaling in 2D games (MVC2, CVS, KOF, etc.).
The fix is enabled by default as to keep the current behaviour.
I tested in standalone + libretro and it works perfectly on the fly.
Thanks to @blueminder for the instructions :)
Closes https://github.com/flyinghead/flycast/issues/1223

Adds option to enable/disable "Fix Upscale Bleeding Edge" - Standalone/Libretro

---

core/rend/vulkan/vk_context_lr.cpp
core/rend/vulkan/vk_context_lr.h
shell/libretro/libretro.cpp

Currently if the Libretro core is built with per-pixel support then the option will always be available to the user, even when using a renderer that doesn't support it (e.g. GLES). It's not rare to see people confused because they have glitchy eyes in Sonic or Shenmue for example while they properly have "Per-Pixel" selected in the core options, because it silently falls back to per-triangle without any indication.
This PR will check if the current renderer supports per-pixel by using the hasPerPixel() function (I had to add it for VK since it didn't exist for the Libretro core), if it's not supported then the 2 values here will be nulled out: https://github.com/flyinghead/flycast/blob/056a02357d46886f42249407e83bf598b599ee4d/shell/libretro/libretro_core_options.h#L349 so it doesn't …

[Libretro] Check for per-pixel compatibility and hide the option if not supported

---

core/types.h

Use angle brackets for including pthread.h

types.h: use angle brackets for system include

---

.github/workflows/c-cpp.yml

Fix the `ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)` error introduced by Xcode 15.
Bumping to use Xcode 15.3 since the problem seems to be gone without adding any workaround flags
May have to use other workarounds as stated from the Apple docs:
https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking
e.g. adding `-ld64` / `-Wl,-ld_classic`

Fix Xcode 15 linker error

---

core/cheats.cpp

For some reason every occurence of this cheat you can find online is broken and it's because the value is incorrect. It's actually supposed to be same as PAL version of the game! (hence why the viewport gets shrunk instead of expanded)
Sidenote: While the game has native widescreen option, it works really poorly
Before
After

Cheats: Tokyo Xtreme Racer 2 fix

---

shell/apple/generate_xcode_project.command

User with `gnu-sed` installed would break the BSD style sed command

Always use BSD sed in generate_xcode_project helper

---

core/cheats.cpp

Adds widescreen cheat for **Faster Than Speed** (Atomiswave version not the DC conversion). Made from scratch.
I apologize if the placement in the file is wrong. I assumed the games are sorted by release date. Feel free to correct it!
Before:
After:

Cheats: Faster Than Speed (Atomiswave) - Widescreen cheat

---

core/cheats.cpp

Adds widescreen cheat for NTSC version of Sega GT. It's a port of the PAL version.

Cheats: Sega GT (USA) - Widescreen cheat

---

shell/uwp/http_client.cpp

Fix for UWP when building for other architectures (win32, arm, arm64)
> D:\a\flycast\flycast\shell\uwp\http_client.cpp(107,19): error C2664: 'void Windows::Web::Http::Headers::HttpContentHeaderCollection::ContentLength::set(Platform::IBox<unsigned __int64> ^)': cannot convert argument 1 from 'size_t' to 'Platform::IBox<unsigned __int64> ^' [D:\a\flycast\flycast\build\flycast.vcxproj]

uwp: fix http ContentLength assignment

---

core/ui/gui.cpp
shell/apple/emulator-osx/emulator-osx/osx-main.mm

> [DEBUG] People keep stumbling on this problem and using "" as identifier in the root of a window instead of "##something".
- The crash only happens in Debug build
- Fix Xcode 15 console pretty print as well

Fix macOS debug build UI crash

---

core/audio/audiobackend_oboe.cpp

Convert sampling rate by using Oboe since converting by underlying APIs prevent us from getting a low latency stream

[Android] Fix aptX Adaptive's Dynamic Low Latency mode

---

.github/workflows/crowdin_prep.yml
.github/workflows/crowdin_translate.yml

Fix the following warning in https://github.com/flyinghead/flycast/actions/runs/10118310701:
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/setup-python@v4. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

ci: bump actions/setup-python to v5

---

core/rec-ARM64/rec_arm64.cpp

`sh4_core.h` has defines for symbols like `r` and `pr` which conflict with the variable names in `arm64_unwind.h` and cause even deeper errors over in `wingdi.h(4954)` and `wincrypt.h(4741)`.
Swapping the include order avoids this collision.
Fixes Windows on ARM builds: https://github.com/flyinghead/flycast/issues/545

Fix `arm64_unwind.h` include-order

---

core/ui/gui.cpp

When entering an error or contentpath warning popup, there are two `ImguiStyleVar` on the stack. Within the pop-up frame, an additional `ImguiStyleVar` is added. When the popup ends, there is technically one more ImguiStyleVar on the internal stack than when we entered the popup, causing an assert to hit:
```
Program: G:\flycast\out\build\x64-Debug\flycast.exe
File: G:\flycast\core\deps\imgui\imgui.cpp
Line: 10104
Expression: SizeOfStyleVarStack >= g.StyleVarStack.Size && "PushStyleVar/PopStyleVar Mismatch!"
```
These nested imgui RAII objects need to be scoped such that the stack is preserved both upon entry and exit of these popups to avoid these asserts.

Fix `{Push,Pop}StyleVar` assert

---

core/rend/vulkan/overlay.cpp
core/rend/vulkan/texture.cpp
core/rend/vulkan/vk_context_lr.h
core/rend/vulkan/vulkan_context.h

Uses compile-time type-information provided by vulkan-hpp to automatically determine a vulkan-object's `objectType` when calling `setObjectName`.

vk: Determine object type enum when setting object name

---

core/rend/vulkan/vulkan_context.cpp

Rather than electing the first physical device it finds, and falling back on the first-listed GPU: a series of stable-partitions are done so that the "least compromising" GPU is selected based on a series of criteria.
It will now maximally try to find a GPU that(in order of priority):
* Is a discrete GPU
* Supports `R5G5B5`/`R5G6B5A1`/`R4G4B4A4`
* Supports `fragmentStoresAndAtomics`
In the case that a system has two dGPUs and one of them supports optimal-formats, the optimal-format one is selected
In the case that a system has an iGPU and the dGPU and they both support optimal formats, the dGPU is selected.
In the case that a system has an iGPU and the dGPU and the dGPU doesn't support optimal formats, the dGPU is still selected.

vk: Refactor physical device selection

---

core/rend/vulkan/vulkan_context.cpp

* Uses a utility-lambda for repeated extension-adding logic
* Uses an `std::set` for the list of available extensions for quick queries
* `VK_EXT_DEBUG_REPORT` and `VK_EXT_DEBUG_UTILS` aren't device extensions and don't need to be here. They are instance extensions
* Each extension that is tested to be added has a corresponding log message for if it was enabled or if it was unavailable
```
00:00:162 rend\vulkan\vulkan_context.cpp:427 N[RENDERER]: Device extension enabled: VK_KHR_swapchain
00:00:162 rend\vulkan\vulkan_context.cpp:427 N[RENDERER]: Device extension enabled: VK_KHR_get_memory_requirements2
00:00:162 rend\vulkan\vulkan_context.cpp:427 N[RENDERER]: Device extension enabled: VK_KHR_dedicated_allocation
00:00:162 rend\vulkan\vulkan_context.cpp:430 N[RENDERER]: Device extension …
```

vk: Refactor device/instance extension enablement

---

core/rend/vulkan/texture.h
core/rend/vulkan/vulkan_driver.h

This addresses the `BestPractices-Arm-vkCreateSampler-different-wrapping-modes` message from ARM: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/65b79bac615ec1c47ab61a02d55a3bba871b56b9/layers/best_practices/bp_descriptor.cpp#L95-L100
The `W`-axis for these samplers is always unused, it's never the case that these samplers are going to be used for 3D textures. ARM suggests trying to keep all of the wrapping-modes the same if possible for performance.
`wRepeat` will be set to the same value as `vRepeat` to try and encourage all three wrapping-modes to be the same.

vk: Use matching u/v/w sampler address-mode when possible

---

core/rend/vulkan/quad.cpp
core/rend/vulkan/quad.h
core/rend/vulkan/vk_context_lr.cpp
core/rend/vulkan/vulkan_context.cpp

Hashes the contents of the `QuadBuffer` vertex-data such that data is only uploaded when the vertices actually change rather than every frame.

vk: Optimize redundant `QuadBuffer` uploads

---

core/rend/vulkan/pipeline.h
core/rend/vulkan/quad.cpp
core/rend/vulkan/vulkan_driver.h

This addresses the `BestPractices-Arm-vkCreateSampler-lod-clamping` message from ARM: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/65b79bac615ec1c47ab61a02d55a3bba871b56b9/layers/best_practices/bp_descriptor.cpp#L103-L110
Rather than clamping the LOD in the samplers, instead rely on the Image-View's `vk::ImageSubresourceRange` to limit the number of sampled LODs.
Currently, only game-textures actually have MipMaps, so this does not introduce any additional mip-map sampling or filtering anywhere. If any code want's to actually limit the number of LODs sampled, then they would allocate an additional ImageView for the range of MipMaps to be sampled.

vk: Disable LOD clamping in samplers

---

core/rend/vulkan/drawer.cpp
core/rend/vulkan/oit/oit_drawer.cpp
core/rend/vulkan/texture.cpp
core/rend/vulkan/vulkan_context.cpp
core/rend/vulkan/vulkan_context.h
core/rend/vulkan/vulkan_driver.h
core/rend/vulkan/vulkan_renderer.cpp

Adds a new RAII-based utility type for adding diagnostic information to command buffers. Enabled only when `VK_DEBUG` is set to `1`.
[This allows GPU tooling such as RenderDoc and NSight to have additional diagnostic information attached to each command buffer](https://wunkolo.github.io/post/2024/09/gpu-debug-scopes/) to help with diagnosing rendering issues.
Before:
After:

vk: Add `CommandBufferDebugScope` utility-type

---

core/rend/vulkan/drawer.cpp
core/rend/vulkan/oit/oit_drawer.cpp
core/rend/vulkan/oit/oit_pipeline.cpp
core/rend/vulkan/pipeline.cpp
core/rend/vulkan/vk_context_lr.cpp
core/rend/vulkan/vk_context_lr.h
core/rend/vulkan/vmallocator.cpp
core/rend/vulkan/vulkan_context.cpp
core/rend/vulkan/vulkan_context.h

The dreamcast uses the last vertex as the provoking vertex, while vulkan uses the first vertex.
This requires an additional call to `setFirstProvokingVertex` to reorder the vertices for all incoming geometry.
With `VK_EXT_provoking_vertex`, the pipeline can designate that the provoking vertex is to be the last vertex, which removes the need to re-order incoming geometry on the CPU.

vk: Add `VK_EXT_provoking_vertex` optimization

---

core/rend/vulkan/drawer.cpp

The full push-constant region is 24 bytes(6 floats), but some of these push-constant writes only wrote 20 bytes of data(5 floats). Causing 4 bytes at the end to be left undefined.
Resolved by pushing an extra zero.

vk: Fix undefined push-constant data

---

core/rend/vulkan/oit/oit_pipeline.h
core/rend/vulkan/oit/oit_shaders.cpp
core/rend/vulkan/pipeline.cpp
core/rend/vulkan/pipeline.h
core/rend/vulkan/shaders.cpp

Rather than using `VK_FORMAT_R8G8B8A8_UINT` for these vertex attributes and then dividing by `255.0` in each of the shaders, the `VK_FORMAT_R8G8B8A8_UNORM` format will automatically remap byte components into the `0.0-1.0` range and removes the need to do the extra divisions or castings within the shader.

vk: Use `VK_FORMAT_R8G8B8A8_UNORM` for vertex colors

---

core/rend/vulkan/oit/oit_pipeline.cpp
core/rend/vulkan/oit/oit_pipeline.h
core/rend/vulkan/pipeline.cpp
core/rend/vulkan/pipeline.h

Disables the naomi2 vertex input attribute when emitting non-naomi2 pipelines. This addresses some validation messages involving unused vertex inputs and optimizes the bandwidth of the input assembler a little bit for non-naomi2 games.

vk: Remove naomi2 vertex attributes when not needed

---

core/rend/vulkan/vk_context_lr.cpp

Used [here](https://github.com/flyinghead/flycast/blob/e221f6fed2964d83c871384fc19a06541ce76aba/core/rend/vulkan/vk_context_lr.cpp#L131).

fix missing include

---

shell/libretro/libretro.cpp
shell/libretro/oslib.cpp

If the BIOS doesn't exist in system/dc/ the core will now check in the game directory as a fall back.
Using `g_roms_dir` which is initialized in `retro_load_game()`: https://github.com/flyinghead/flycast/blob/da3cfd9d587d892aa7a3abefe919faa1078f4766/shell/libretro/libretro.cpp#L2045

[Libretro] Add game dir as fall back for arcade BIOSes

---

shell/apple/emulator-osx/emulator-osx/osx-main.mm
shell/apple/generate_xcode_project.command

- Fix`PhaseScriptExecution failed` error
- Fix Flycast cannot be launched from debugger 
- NSLog prettyprint for Xcode 16

Update Xcode project generator

---

core/audio/audiobackend_oss.cpp

Audio and record initializations are unified by providing helper functions for opening the audio device and for setting the device parameters. The ioctl calls are properly checked for errors and log an appropriate error message. The init fails if the requested parameters are not supported by the device, i.e. 44.1kHz 16bit stereo for playback. This provides consistent behavior with all the other audio backends.

oss: cleanup and unification

---

.github/workflows/c-cpp.yml

> ubuntu-latest pipelines will use ubuntu-24.04 soon. For more details, see https://github.com/actions/runner-images/issues/10636
GitHub Actions is making the transition to ubuntu-24.04 when using ubuntu-latest but the `ppa:christianrauch/libdecoration` is not compatible with this version so let's stick to ubuntu-22.04 for now to prevent failing jobs

ci: force ubuntu-22.04 on libretro-x86_64-pc-linux-gnu target

---

core/build.h
core/linux/context.cpp
core/oslib/host_context.h
core/ui/gui.cpp

CMake already triggers a fatal error if the architecture is not supported so it is unlikely that the deleted code in this PR has any use

build: drop unsupported architectures

---

core/cfg/option.cpp
core/hw/arm7/arm7.cpp
core/hw/modem/modem.cpp
core/rend/dx11/dx11context.cpp
core/rend/dx9/d3d_overlay.cpp
core/rend/vulkan/drawer.cpp
core/rend/vulkan/vmallocator.h
core/windows/winmain.cpp

I fixed some warnings that I encountered when build with GCC/Clang on Windows.

fix compiler warnings

---

core/rend/gles/gldraw.cpp

```cpp
gl.videorouting.framebuffer = std::make_unique<GlFramebuffer>(targetWidth, targetHeight, true, true);
```
cannot be called before
```cpp
saveCurrentFramebuffer();
```

[macOS] Fix booting game stuck with Video Routing

---

core/rend/vulkan/vulkan_context.cpp

Some notable devices support native RGB8 color-attachments:
https://vulkan.gpuinfo.org/listdevicescoverage.php?optimaltilingformat=R8G8B8_UNORM&featureflagbit=COLOR_ATTACHMENT
This removes the need to do a manual RGBA->RGB format conversion on the CPU in favor of a direct memcpy from the downloaded texture, when available.

vulkan: Allow native `RGB8` screenshot framebuffers when available

---

core/rend/vulkan/vulkan_context.cpp
core/rend/vulkan/vulkan_context.h

Use a series of stable-partitions to sort the list of available formats to find the best candidate surface-format/color-space that is a non-sRGB format being presented in an sRGB color-space. Vulkan mandates that all surface formats that have SRGB forms must also support a UNORM form.
This is basically just RGBA8/BGRA8 on all platforms still, but in a way that is still capable of falling back to secondary formats in a stable way in the case that the primary choice is not available.  Mobile devices especially have a LOT of secondary HDR surface formats and other weird formats that can be used to present such as RGBA16 or RGBA565. With stable partitions, if we can't get our best option then there is always a "next best thing" to fall back on rather than relying on the driver-order.

vk: Refactor swapchain format selection

---

core/hw/maple/maple_devs.cpp
core/sdl/dreamconn.cpp
core/sdl/dreamconn.h
core/sdl/sdl.cpp
core/sdl/sdl_gamepad.h

This PR enables the usage of VMUs and Rumble Packs with original Dreamcast Controllers connected to MacOS/Linux/Windows using the [DreamcastControllerUsbPico](https://github.com/OrangeFox86/DreamcastControllerUsbPico) Raspberry Pi Pico-based USB-Adapter.
By default, the USB-Adapter provides the following devices:
- USB HID with support for analog triggers (e.g., to be used by any emulator/game)
- USB MSC exposing the VMU contents as a removable media (e.g., to copy savegames between emulators and actual hardware)
- USB CDC serial device for communication with the Maple Bus (i.e., enabling arbitrary MapleIO)
Using the USB CDC serial device, this PR piggybacks on the handler for DreamConn+ Controllers as discussed [here](https://github.com/flyinghead/flycast/issues/1305). It currently …

VMUs and Rumble Packs with Original Dreamcast Controllers

---

core/sdl/dreamconn.cpp
core/sdl/dreamconn.h
core/sdl/sdl.cpp

PR renames `DreamPort` to `DreamPicoPort` to differentiate from another Dreamcast peripheral using the same name. Renaming has already been done in the [project](https://github.com/OrangeFox86/DreamPicoPort) and in [SDL](https://github.com/libsdl-org/SDL/pull/12325).

Rename DreamPort to DreamPicoPort

---

shell/android-studio/flycast/build.gradle
shell/android-studio/gradle/libs.versions.toml
shell/android-studio/gradle/wrapper/gradle-wrapper.properties

Oboe 1.9.3 has support for 16kb page sizes
Changelog for SDL 2.32.2
- Fixed stack overflow when setting thread debug names on Windows
- Fixed flushing audio forever in some cases when recording PulseAudio on Linux
- Fixed a crash when initializing with controllers connected on macOS
- Added SDL_HINT_JOYSTICK_HAPTIC_AXES to specify how many haptic axes a device has

Misc updates

---

.github/workflows/c-cpp.yml

This will remove the following warning in GitHub Actions:
> ninja 1.12.1 is already installed and up-to-date. To reinstall 1.12.1, run: brew reinstall ninja
As ninja is already installed in `macos-latest` runners

ci: remove ninja installation for macos runner

---

core/hw/mem/addrspace.cpp
core/hw/mem/addrspace.h
core/ui/gui.cpp

In Advanced Settings tab:
* Display current VM addresses
* Add options to tweak GDB debugging
* move _Serial Console_ option
All these changes honors `ENABLE_GDB_SERVER`.

Allow tweak GDB options

---

core/sdl/sdl.cpp

Flycast has a bug that happens when you have multiple monitors.
If I have 2 monitors running, and move Flycast to monitor 2, then exit, it saves so the next time you load up Flycast it will start on that screen. This is nice until you unplug the 2nd monitor before changing it back. When this happens, you can start Flycast but cannot see it, unless you press F11 to make it fullscreen, but then when you hit it again, it goes back to the screen not plugged in and cannot be seen.
I decided to add a check that verifies if the saved window position is on a currently connected display. If not, it resets the window position to the primary display, preventing Flycast from opening on a monitor that is no longer connected and becoming invisible to the user.

Screen position bug fix

---

core/deps/picotcp/modules/pico_ipv4.c
core/deps/picotcp/modules/pico_tcp.c

Hi Development Team,
I identified potential vulnerabilities in clone functions in `core/deps/picotcp/modules/pico_tcp.c` and `core/deps/picotcp/modules/pico_ipv4.c` sourced from [virtualsquare/picotcp](https://github.com/virtualsquare/picotcp). This issue, originally reported in [CVE-2023-35849](https://nvd.nist.gov/vuln/detail/CVE-2023-35849), was resolved in the repository via this commit https://github.com/virtualsquare/picotcp/commit/4b9a16764f2b12b611de9c34a50b4713d10ca401.
This PR applies the corresponding patch to handle potential null pointer dereference in this codebase.
Please review at your convenience. Thank you!

Fix potential vulnerable cloned function

---

CMakeLists.txt

`--execute-only` is enabled by default on openbsd.
This PR fixes the following error on openbsd/arm64:
```
ld: error: cannot place CMakeFiles/flycast.dir/core/hw/aica/dsp_arm64.cpp.o:(.text) into .text: --execute-only does not support intermingling data and code
```
https://github.com/scribam/flycast/actions/runs/15235573297/job/42848889115#step:4:1443

cmake: disable link option --execute-only on openbsd

---

core/ui/settings.cpp

I tried to compile with GDB support but it gave an error in settings.cpp, just a small fix.
Sorry my english.

fix: added missing addrspace inclusion in settings.cpp for GDB_SERVER

---

core/sdl/dreamconn.cpp
core/sdl/dreamconn.h

Extracted from #1989 
This fixes a bug where send operations which expect a response would crash Flycast, because it would lock the non-reentrant mutex once in `send(txMsg, rxMsg)`, then call `send(msg)` which locks the mutex again.
So, for example, VMU graphics/buzzer stuff would work, since no response is expected, but as soon as the game tried to read VMU save data, the emulator would crash.

DreamConn: do not lock mutex multiple times
