flyinghead/flycast

core/build.h
core/linux-dist/main.cpp
core/linux/common.cpp

Makefile for Emscripten build has been dropped in commit 1333d6f776d4d6cb326ea2caeb422eb92e098e78.

Remove Emscripten support entirely

---

core/hw/sh4/sh4_mem.h
core/linux/common.cpp
core/log/BitSet.h
core/rec-x86/rec_x86_driver.cpp
core/types.h

Some required changes for my WIP CMake branch :slightly_smiling_face: 
With this, I can compile on Ubuntu x64, Visual Studio (x86 and x64) and MacOS : https://dev.azure.com/scribam/reicast-emulator/_build/results?buildId=15

Misc platform changes

---

core/deps/chdr/flac.h
shell/reicast.vcxproj

Forgot to update the "dirent" path in the Visual Studio project after rebase :confused:

Small integration fixes/improvements

---

shell/reicast.sln
shell/reicast.vcxproj
shell/reicast.vcxproj.filters

Tested on Visual Studio 2019 + Windows 10

msvc: Fix Visual Studio solution

---

shell/apple/emulator-osx/emulator-osx/EmuGLView.swift
shell/apple/emulator-osx/emulator-osx/osx-main.mm

Tested on MacBook Pro 16", macOS 10.15.2

Handle Retina / DPI correctly

---

core/nullDC.cpp
core/rend/gui.cpp

New UI with predefined values, since the original slider won't work for a large range for 0~800
first time to play with Dear ImGui, feel free to edit

Enable upscaling for up to 8x SSAA

---

core/hw/naomi/awcartridge.cpp
core/hw/naomi/naomi_cart.h
core/reios/gdrom_hle.cpp
core/stdclass.cpp
core/types.h

Add NOMINMAX for MSVC and use <algorithm>

---

shell/android-studio/reicast/src/main/jni/src/utils.cpp

android: remove relative path to include zip.h

---

core/hw/modem/modem.cpp

Improve modem receive speed for realtime online games.
I'm still not sure the 62us is appropriate.

[MODEM] recv tune. set small callback_cycles to recv fllowing data quickly

---

core/cfg/cl.cpp
core/emitter/x86_emitter.h
core/hw/aica/dsp_x64.cpp
core/hw/arm7/arm7.cpp
core/hw/pvr/Renderer_if.cpp
core/hw/pvr/Renderer_if.h
core/hw/sh4/dyna/driver.cpp
core/hw/sh4/modules/serial.cpp
core/linux/common.cpp
core/linux/context.cpp
core/linux/posix_vmem.cpp
core/log/ConsoleListenerNix.cpp
core/oslib/audiobackend_coreaudio.cpp
core/rec-ARM/ngen_arm.S
core/rec-ARM/rec_arm.cpp
core/rec-x64/rec_x64.cpp
core/rend/gles/gles.cpp
core/rend/gles/gltex.cpp
core/rend/gles/imgui_impl_opengl3.cpp
core/rend/gui.cpp
core/rend/gui_util.cpp
core/rend/vulkan/vulkan_context.cpp
core/sdl/sdl.cpp
core/stdclass.cpp
core/types.h
core/wsi/gl4funcs.cpp
core/wsi/gl_context.h
core/wsi/osx.cpp
core/wsi/osx.h
core/wsi/sdl.cpp

`__MACH__` also replaced by ` __APPLE__` because GNU Hurd declares it as well and I don't think it is currently supported by Flycast

Replace OS_DARWIN by __APPLE__

---

.github/workflows/c-cpp.yml

ccache helps to decrease the compilation time, only available on macOS and Ubuntu

github-actions: add ccache support

---

.github/workflows/android.yml
shell/android-studio/reicast/build.gradle
shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/AudioBackend.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/JNIdc.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/periph/InputDeviceManager.java
shell/android-studio/reicast/src/main/jni/Android.mk

These changes replace the Android build process with Makefiles.

Use CMake for Android build and add GitHub CI

---

shell/apple/emulator-osx/emulator-osx/osx-main.mm
shell/apple/reicast.xcworkspace/xcshareddata/xcdebugger/Breakpoints_v2.xcbkptlist

Ignore EXC_BAD_ACCESS in debug mode. Bypass SIGBUS signal in lldb using Breakpoint Action

[Xcode] Handle EXC_BAD_ACCESS & SIGBUS automatically during debug

---

core/oslib/audiobackend_coreaudio.cpp

From: https://github.com/reicast/reicast-emulator/pull/1880

macOS: Fixed audio clicking on external speakers

---

core/hw/maple/maple_jvs.cpp

Explanation : https://www.viva64.com/en/w/v1023/

maple: fix potential mem leaks if vector reallocation fails

---

shell/linux/org.flycast.Flycast.metainfo.xml

Required for Flatpak.
Relates to https://github.com/flyinghead/flycast/issues/218.

Add Appstream metadata file

---

core/rend/game_scanner.h

Fix scanner cannot be stopped also

Re-enable the content path warning dialog

---

.github/workflows/c-cpp.yml

github actions: remove flac installation from macos

---

.github/workflows/android.yml
.github/workflows/c-cpp.yml

Avoid Github Actions failures on forks due to missing S3_SECRET_KEY

github actions: authorize aws actions on main repository only

---

core/rend/dx9/d3d_shaders.h
core/windows/rawinput.h

- Use correct case for `d3dx9shader.h`
- Add `<algorithm>` for `std::replace`

Minor include header changes

---

shell/apple/emulator-osx/emulator-osx/EmuGLView.swift
shell/apple/emulator-osx/emulator-osx/emulator-osx-Bridging-Header.h
shell/apple/emulator-osx/emulator-osx/osx-main.mm

Support Fast Forward in macOS

---

core/cfg/option.cpp
core/cfg/option.h
core/network/ggpo.cpp
core/rend/gui.cpp
shell/libretro/option.cpp

* Adds Frame Delay to Settings
* Displays Frame Delay in Stats

ggpo: add frame delay to settings

---

CMakeLists.txt
shell/apple/emulator-ios/emulator/FlycastViewController.mm
shell/apple/emulator-ios/emulator/ios_keyboard.h

PR adds in support for iOS keyboards using GCKeyboard

iOS Keyboard Support

---

shell/libretro/libretro.cpp

As mentioned in #354, this fixes the middle mouse button for the Libretro core :)

[Libretro] Middle mouse fix

---

.github/workflows/c-cpp.yml

Syncing with the others workflows

ci: simplify C/C++ CI workflow

---

shell/apple/emulator-ios/emulator/ios_keyboard.h

Adds in more keys (international, language, left+right meta). Also added in a gui hotkey when pressing Left Alt and Left Meta

[iOS] Add more keyboard keys, gui hotkey

---

.github/workflows/c-cpp.yml
CMakeLists.txt
shell/apple/generate_xcode_project.command

Use cmake install and CMAKE_INSTALL_PREFIX to specify the output directory of the generated artifact

ci: add cmake install and refactor artifact generation

---

shell/apple/emulator-osx/emulator-osx/SDLMain.mm
shell/apple/emulator-osx/emulator-osx/osx-main.mm

[macOS] Enable "New Instance" in File and Dock menu for SDL

---

core/sdl/sdl.cpp
core/sdl/sdl_gamepad.h

sdl: fix joystick rumble

---

core/sdl/sdl_gamepad.h

Reborn of https://github.com/flyinghead/flycast/pull/311, fixes https://github.com/flyinghead/flycast/issues/309.

Add default coin mapping

---

.github/workflows/c-cpp.yml

Fix #577 but break ccache support (so I remove it for the time being).

ci: use xcode for macos

---

.github/workflows/crowdin_prep.yml
.github/workflows/crowdin_translate.yml

ci: add distribution input to actions/setup-java@v3

---

.github/workflows/crowdin_prep.yml
.github/workflows/crowdin_translate.yml

https://github.com/flyinghead/flycast/runs/6135845339?check_suite_focus=true

ci: fix java-version for actions/setup-java

---

core/cfg/option.cpp
core/cfg/option.h
core/rend/dx11/dx11_renderer.cpp
core/rend/dx11/dx11_shaders.cpp
core/rend/dx11/dx11_shaders.h
core/rend/dx11/oit/dx11_oitshaders.cpp
core/rend/dx11/oit/dx11_oitshaders.h
core/rend/dx9/d3d_shaders.cpp
core/rend/dx9/d3d_shaders.h
core/rend/gl4/abuffer.cpp
core/rend/gl4/gl4.h
core/rend/gl4/gl4naomi2.cpp
core/rend/gl4/gldraw.cpp
core/rend/gl4/gles.cpp
core/rend/gl4/glsl.h
core/rend/gles/gles.cpp
core/rend/gles/gles.h
core/rend/gles/naomi2.cpp
core/rend/gui.cpp
core/rend/vulkan/oit/oit_pipeline.cpp
core/rend/vulkan/oit/oit_pipeline.h
core/rend/vulkan/oit/oit_shaders.cpp
core/rend/vulkan/oit/oit_shaders.h
core/rend/vulkan/pipeline.cpp
core/rend/vulkan/pipeline.h
core/rend/vulkan/shaders.cpp
core/rend/vulkan/shaders.h
core/rend/vulkan/utils.h
shell/libretro/libretro_core_options.h
shell/libretro/option.cpp

Native depth interpolation option to help AMD gpus

---

shell/apple/emulator-osx/emulator-osx/SDLMain.mm

[macOS] Handle Dock menu's Quit action

---

CMakeLists.txt
core/rend/TexCache.h
core/rend/gl4/glsl.h
core/rend/gles/gles.cpp
core/rend/gles/gltex.cpp
core/rend/gui.cpp
core/rend/transform_matrix.h
core/rend/vulkan/vulkan_context.cpp
core/wsi/switcher.cpp
core/wsi/wgl.cpp
core/wsi/xgl.cpp

rename `Open GL` to `OpenGL` as well

Stop Apple fanboys from asking where is Metal

---

core/rend/vulkan/commandpool.h
core/rend/vulkan/compiler.cpp
core/rend/vulkan/desc_set.h
core/rend/vulkan/drawer.cpp
core/rend/vulkan/oit/oit_buffer.h
core/rend/vulkan/oit/oit_drawer.cpp
core/rend/vulkan/oit/oit_pipeline.cpp
core/rend/vulkan/oit/oit_pipeline.h
core/rend/vulkan/oit/oit_renderpass.cpp
core/rend/vulkan/overlay.cpp
core/rend/vulkan/pipeline.cpp
core/rend/vulkan/pipeline.h
core/rend/vulkan/quad.cpp
core/rend/vulkan/quad.h
core/rend/vulkan/texture.cpp
core/rend/vulkan/vk_context_lr.cpp
core/rend/vulkan/vk_context_lr.h
core/rend/vulkan/vulkan_context.cpp
core/rend/vulkan/vulkan_context.h
core/rend/vulkan/vulkan_renderer.h

Vulkan-Hpp provides enhanced versions of the commands and enhanced structure constructors which simplify the handling of array data.

vulkan: simplify function calls

---

CMakeLists.txt

Indent everything with tabs instead of a mix of spaces and tabs to make future PR easier.

cmake: normalize whitespaces

---

.github/workflows/switch.yml
CMakeLists.txt

Commit https://github.com/devkitPro/pacman-packages/commit/679c856eb1a0b5e86a41f2edbdfe055d3d22a253 updates CMake compiler flags. I hope the performance regression which led to commit https://github.com/flyinghead/flycast/commit/6538360fe1828b1daa808d63d42d826faed1e169 is fixed but, since I don't have a switch, testing and feedback are welcome.

ci: use devkitpro/devkita64:latest

---

shell/apple/emulator-osx/MacOSXBundleInfo.plist.in

Mark Flycast as a game for Launchpad

---

core/hw/pvr/Renderer_if.cpp

Fix renderer not resized when window size changes

---

core/rend/gui.cpp

Responsive size Boxart

---

core/rend/game_scanner.h

If everything is good, this PR closes #735

[Game List] Separate DC and arcade games

---

CMakeLists.txt
core/cfg/option.cpp
core/cfg/option.h
core/debug/debug_agent.h
core/debug/gdb_server.cpp
core/debug/gdb_server.h
core/emulator.cpp
core/nullDC.cpp
core/rend/dx11/dx11_driver.h
core/rend/dx9/dx9_driver.h
core/rend/gles/opengl_driver.cpp
core/rend/gles/opengl_driver.h
core/rend/gui.cpp
core/rend/imgui_driver.h
core/rend/vulkan/vulkan_driver.h

1. Enabled GDB server, compile fix for MSVC, added GDB option to config
2. Fixed handling of unknown vpackets (and vMustReplyEmpty should be "unknown", it exists to test this behaviour)
4. Added a GDBWaitForConnection option to allow for debugging from bootstrap/main()
5. Fixed UI to allow for "Waiting for debugger" and other final frames before a UI state change (e.g., progress bars should now reach 100% instead of 99%)
6. Fixed endianness of registers and memory send to/from GDB - backtrace and frame disassembly now working correctly as a result

Various GDB fixes and improvements

---

.github/workflows/c-cpp.yml
core/rend/vulkan/compiler.cpp

Fix install step where unwanted vulkan files are currently installed (cf. https://github.com/flyinghead/flycast/actions/runs/3669641346/jobs/6203612632#step:11:1399)

deps: update glslang and vulkan

---

CMakeLists.txt
core/deps/implot/LICENSE
core/deps/implot/implot.cpp
core/deps/implot/implot.h
core/deps/implot/implot_internal.h
core/deps/implot/implot_items.cpp
core/profiler/fc_profiler.cpp
core/profiler/fc_profiler.h
core/rend/gui.cpp

Implemented CPU frame time (ms) graphs per thread. Adds ImPlot as a dependency.

Basic CPU graphs using ImPlot

---

core/rend/vulkan/vulkan_context.cpp

Attempt to fix https://sentry.io/organizations/flycast/issues/3842427499/

vulkan: return an error if no physical devices found

---

shell/android-studio/flycast/src/main/java/com/reicast/emulator/emu/NativeGLView.java

`android.view.View#getDisplay` requires API level 17

android: use getDefaultDisplay with android api level < 17

---

core/rend/gl4/gles.cpp
core/rend/gles/gles.cpp

`gl_create_resources()` always returns true

gl,gl4: simplify gl_create_resources calls

---

CMakeLists.txt
core/network/net_platform.h

Credits to @c64skin. I did a slight modification in CMakeLists.txt.
Fix #899

openbsd fixes

---

core/rend/gui.cpp

Fix compilation with `#define IMGUI_DISABLE_OBSOLETE_FUNCTIONS` and `#define IMGUI_DISABLE_OBSOLETE_KEYIO`

deps: remove imgui obsolete functions

---

core/deps/implot/implot.cpp
core/deps/implot/implot_internal.h
core/deps/implot/implot_items.cpp

Reference: https://github.com/epezent/implot/pull/449

deps: update implot to fix IMGUI_DEFINE_MATH_OPERATORS requirements

---

.github/workflows/c-cpp.yml
CMakeLists.txt
core/rend/vulkan/compiler.cpp

distfiles.macports.org is outdated, that is why I removed it

deps: update glslang and Vulkan-Headers to sdk-1.3.243.0

---

core/deps/imgui/backends/imgui_impl_dx11.cpp
core/deps/imgui/backends/imgui_impl_dx11.h
core/deps/imgui/backends/imgui_impl_dx9.cpp
core/deps/imgui/backends/imgui_impl_dx9.h
core/deps/imgui/backends/imgui_impl_vulkan.cpp
core/deps/imgui/backends/imgui_impl_vulkan.h

Update imgui backends for DX9, DX11 and Vulkan using imgui v1.89.5. I also reapplied some changes specific to Flycast.

Update imgui backends

---

.github/workflows/c-cpp.yml

Sync with Vulkan SDK 1.3.250. glslang has already been updated

deps: update Vulkan-Headers and VulkanMemoryAllocator

---

.github/workflows/c-cpp.yml

`1.3.250.0` is deleted by LunarG

deps: update vulkan to `1.3.250.1`, fix 404 on macOS

---

README.md

Retail Mode isn't supported anymore. Enough said.

(README) Modify Xbox Section

---

CMakeLists.txt
core/hw/aica/dsp_arm32.cpp
core/hw/arm7/arm7_rec_arm32.cpp
core/rec-ARM/arm_unwind.h
core/rec-ARM/rec_arm.cpp
core/windows/win_vmem.cpp

It builds fine but, like for arm64, I don't have a hardware to test.
CI: https://github.com/scribam/flycast/actions/runs/5717908762

uwp: add support for arm

---

.github/workflows/switch.yml

Issues with SDL2 have been resolved

ci: use latest devkitpro docker image

---

shell/libretro/libretro_core_options_intl.h

Something went wrong with the latest libretro translation fetch from crowdin, this commit fixes it

libretro: fix translation

---

shell/android-studio/build.gradle
shell/android-studio/flycast/build.gradle
shell/android-studio/flycast/src/main/AndroidManifest.xml
shell/android-studio/gradle.properties
shell/android-studio/gradle/libs.versions.toml
shell/android-studio/gradle/wrapper/gradle-wrapper.properties
shell/android-studio/settings.gradle

- Upgrade AGP dependency from 8.3.0 to 8.4.1
- Upgrade Gradle version to 8.6
- Use version catalogs

android: update project

---

shell/libretro/oslib.cpp

https://git.libretro.com/libretro/flycast-upstream/-/pipelines/273206

libretro build fix on apple

---

.github/workflows/c-cpp.yml

ci: remove brew zstd

---

core/network/miniupnp.cpp

miniupnp: add support for api version 18

---

core/hw/sh4/dyna/ssa.h

I have no experience with this codebase so someone should probably review it before merging.

Fix wrong opcode comparison

---

.gitlab-ci.yml

https://git.libretro.com/libretro/flycast-upstream/-/pipelines/340928

libretro: build osx-x64 build on new builder

---

core/rend/dx11/dx11context.cpp
core/rend/dx11/dx11context.h
core/rend/dx11/dx11context_lr.cpp

This allow to use DXGI 1.6 and latest D3D11 version (11.4)

Use DXGI 1.6 and D3D11_4

---

core/ui/gui.cpp

Added discreet rounded borders, which make the interface more modern and welcoming
Before:
After:

[GUI] Adding Rounded Borders

---

core/debug/gdb_server.cpp
core/hw/maple/maple_devs.cpp
core/hw/pvr/elan.cpp
core/network/ggpo.cpp
core/rec-ARM/rec_arm.cpp
core/rend/vulkan/quad.h

No major changes, just for code quality.

Misc: Remove Duplicated Semicolons

---

.github/workflows/switch.yml

Regression introduced by PR https://github.com/flyinghead/flycast/pull/1842

ci: fix switch libretro artifact location
